spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://admin:admin123@localhost:27017/franchises_db?authSource=admin}
      database: ${MONGODB_DATABASE:franchises_db}

logging:
  level:
    com.nequi.franchises.franchises: DEBUG